(cl:defpackage mbf_msgs-srv
  (:use )
  (:export
   "CHECKPATH"
   "<CHECKPATH-REQUEST>"
   "CHECKPATH-REQUEST"
   "<CHECKPATH-RESPONSE>"
   "CHECKPATH-RESPONSE"
   "CHECKPOINT"
   "<CHECKPOINT-REQUEST>"
   "CHECKPOINT-REQUEST"
   "<CHECKPOINT-RESPONSE>"
   "CHECKPOINT-RESPONSE"
   "CHECKPOSE"
   "<CHECKPOSE-REQUEST>"
   "CHECKPOSE-REQUEST"
   "<CHECKPOSE-RESPONSE>"
   "CHECKPOSE-RESPONSE"
  ))

