// Auto-generated. Do not edit!

// (in-package mbf_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let GetPathActionGoal = require('./GetPathActionGoal.js');
let GetPathActionResult = require('./GetPathActionResult.js');
let GetPathActionFeedback = require('./GetPathActionFeedback.js');

//-----------------------------------------------------------

class GetPathAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new GetPathActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new GetPathActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new GetPathActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GetPathAction
    // Serialize message field [action_goal]
    bufferOffset = GetPathActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = GetPathActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = GetPathActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GetPathAction
    let len;
    let data = new GetPathAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = GetPathActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = GetPathActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = GetPathActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += GetPathActionGoal.getMessageSize(object.action_goal);
    length += GetPathActionResult.getMessageSize(object.action_result);
    length += GetPathActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'mbf_msgs/GetPathAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f4d6567e6c5805b81da135676625d187';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    GetPathActionGoal action_goal
    GetPathActionResult action_result
    GetPathActionFeedback action_feedback
    
    ================================================================================
    MSG: mbf_msgs/GetPathActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    GetPathGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: mbf_msgs/GetPathGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Get a path from start_pose or current position to the target pose
    
    # Use start_pose or current position as the beginning of the path
    bool use_start_pose
    
    # The start pose for the path; optional, used if use_start_pose is true
    geometry_msgs/PoseStamped start_pose
    
    # The pose to achieve with the path
    geometry_msgs/PoseStamped target_pose
    
    # If the goal is obstructed, how many meters the planner can relax the constraint in x and y before failing
    float64 tolerance
    
    # Planner to use; defaults to the first one specified on "planners" parameter
    string planner
    
    # use different slots for concurrency
    uint8 concurrency_slot
    
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: mbf_msgs/GetPathActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    GetPathResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: mbf_msgs/GetPathResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Predefined success codes:
    uint8 SUCCESS         = 0
    # 1..9 are reserved as plugin specific non-error results
    
    # Possible error codes:
    uint8 FAILURE         = 50  # Unspecified failure, only used for old, non-mfb_core based plugins
    uint8 CANCELED        = 51  # The action has been canceled by a action client
    uint8 INVALID_START   = 52  #
    uint8 INVALID_GOAL    = 53
    uint8 NO_PATH_FOUND   = 54
    uint8 PAT_EXCEEDED    = 55
    uint8 EMPTY_PATH      = 56
    uint8 TF_ERROR        = 57
    uint8 NOT_INITIALIZED = 58
    uint8 INVALID_PLUGIN  = 59
    uint8 INTERNAL_ERROR  = 60
    uint8 OUT_OF_MAP      = 61
    uint8 MAP_ERROR       = 62
    uint8 STOPPED         = 63  # The planner execution has been stopped rigorously.
    
    # 71..99 are reserved as plugin specific errors
    
    uint32 outcome
    string message
    
    nav_msgs/Path path
    
    float64 cost
    
    
    ================================================================================
    MSG: nav_msgs/Path
    #An array of poses that represents a Path for a robot to follow
    Header header
    geometry_msgs/PoseStamped[] poses
    
    ================================================================================
    MSG: mbf_msgs/GetPathActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    GetPathFeedback feedback
    
    ================================================================================
    MSG: mbf_msgs/GetPathFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GetPathAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = GetPathActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new GetPathActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = GetPathActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new GetPathActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = GetPathActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new GetPathActionFeedback()
    }

    return resolved;
    }
};

module.exports = GetPathAction;
