(cl:in-package rl_planner-srv)
(cl:export '(MAP_STATIC_POSITION-VAL
          MAP_STATIC_POSITION
          MAP_DYNAMIC_VELOCITY_X-VAL
          MAP_DYNAMIC_VELOCITY_X
          MAP_DYNAMIC_VELOCITY_Y-VAL
          MAP_DYNAMIC_VELOCITY_Y
          TRAJECTORIES-VAL
          TRAJECTORIES
          VX-VAL
          VX
          VY-VAL
          VY
          LAST_STATIC_SAFETY_MARGIN-VAL
          LAST_STATIC_SAFETY_MARGIN
          LAST_DYNAMIC_SAFETY_MARGIN-VAL
          LAST_DYNAMIC_SAFETY_MARGIN
          STATIC_SAFETY_MARGIN-VAL
          STATIC_SAFETY_MARGIN
          DYNAMIC_SAFETY_MARGIN-VAL
          DYNAMIC_SAFETY_MARGIN
))