; Auto-generated. Do not edit!


(cl:in-package mbf_msgs-msg)


;//! \htmlinclude GetPathFeedback.msg.html

(cl:defclass <GetPathFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetPathFeedback (<GetPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mbf_msgs-msg:<GetPathFeedback> is deprecated: use mbf_msgs-msg:GetPathFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetPathFeedback>) ostream)
  "Serializes a message object of type '<GetPathFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetPathFeedback>) istream)
  "Deserializes a message object of type '<GetPathFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetPathFeedback>)))
  "Returns string type for a message object of type '<GetPathFeedback>"
  "mbf_msgs/GetPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetPathFeedback)))
  "Returns string type for a message object of type 'GetPathFeedback"
  "mbf_msgs/GetPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetPathFeedback>)))
  "Returns md5sum for a message object of type '<GetPathFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetPathFeedback)))
  "Returns md5sum for a message object of type 'GetPathFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetPathFeedback>)))
  "Returns full string definition for message of type '<GetPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetPathFeedback)))
  "Returns full string definition for message of type 'GetPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetPathFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetPathFeedback
))
