// Generated by gencpp from file rl_planner/rl_state.msg
// DO NOT EDIT!


#ifndef RL_PLANNER_MESSAGE_RL_STATE_H
#define RL_PLANNER_MESSAGE_RL_STATE_H

#include <ros/service_traits.h>


#include <rl_planner/rl_stateRequest.h>
#include <rl_planner/rl_stateResponse.h>


namespace rl_planner
{

struct rl_state
{

typedef rl_stateRequest Request;
typedef rl_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rl_state
} // namespace rl_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl_planner::rl_state > {
  static const char* value()
  {
    return "e0541c399b3508e509e9e93d705eab77";
  }

  static const char* value(const ::rl_planner::rl_state&) { return value(); }
};

template<>
struct DataType< ::rl_planner::rl_state > {
  static const char* value()
  {
    return "rl_planner/rl_state";
  }

  static const char* value(const ::rl_planner::rl_state&) { return value(); }
};


// service_traits::MD5Sum< ::rl_planner::rl_stateRequest> should match
// service_traits::MD5Sum< ::rl_planner::rl_state >
template<>
struct MD5Sum< ::rl_planner::rl_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl_planner::rl_state >::value();
  }
  static const char* value(const ::rl_planner::rl_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_planner::rl_stateRequest> should match
// service_traits::DataType< ::rl_planner::rl_state >
template<>
struct DataType< ::rl_planner::rl_stateRequest>
{
  static const char* value()
  {
    return DataType< ::rl_planner::rl_state >::value();
  }
  static const char* value(const ::rl_planner::rl_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl_planner::rl_stateResponse> should match
// service_traits::MD5Sum< ::rl_planner::rl_state >
template<>
struct MD5Sum< ::rl_planner::rl_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl_planner::rl_state >::value();
  }
  static const char* value(const ::rl_planner::rl_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_planner::rl_stateResponse> should match
// service_traits::DataType< ::rl_planner::rl_state >
template<>
struct DataType< ::rl_planner::rl_stateResponse>
{
  static const char* value()
  {
    return DataType< ::rl_planner::rl_state >::value();
  }
  static const char* value(const ::rl_planner::rl_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_PLANNER_MESSAGE_RL_STATE_H
