// Generated by gencpp from file mbf_msgs/CheckPath.msg
// DO NOT EDIT!


#ifndef MBF_MSGS_MESSAGE_CHECKPATH_H
#define MBF_MSGS_MESSAGE_CHECKPATH_H

#include <ros/service_traits.h>


#include <mbf_msgs/CheckPathRequest.h>
#include <mbf_msgs/CheckPathResponse.h>


namespace mbf_msgs
{

struct CheckPath
{

typedef CheckPathRequest Request;
typedef CheckPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckPath
} // namespace mbf_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mbf_msgs::CheckPath > {
  static const char* value()
  {
    return "59ef27f5ce7e3cc3c7f7a0f823bca55c";
  }

  static const char* value(const ::mbf_msgs::CheckPath&) { return value(); }
};

template<>
struct DataType< ::mbf_msgs::CheckPath > {
  static const char* value()
  {
    return "mbf_msgs/CheckPath";
  }

  static const char* value(const ::mbf_msgs::CheckPath&) { return value(); }
};


// service_traits::MD5Sum< ::mbf_msgs::CheckPathRequest> should match
// service_traits::MD5Sum< ::mbf_msgs::CheckPath >
template<>
struct MD5Sum< ::mbf_msgs::CheckPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mbf_msgs::CheckPath >::value();
  }
  static const char* value(const ::mbf_msgs::CheckPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mbf_msgs::CheckPathRequest> should match
// service_traits::DataType< ::mbf_msgs::CheckPath >
template<>
struct DataType< ::mbf_msgs::CheckPathRequest>
{
  static const char* value()
  {
    return DataType< ::mbf_msgs::CheckPath >::value();
  }
  static const char* value(const ::mbf_msgs::CheckPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mbf_msgs::CheckPathResponse> should match
// service_traits::MD5Sum< ::mbf_msgs::CheckPath >
template<>
struct MD5Sum< ::mbf_msgs::CheckPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mbf_msgs::CheckPath >::value();
  }
  static const char* value(const ::mbf_msgs::CheckPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mbf_msgs::CheckPathResponse> should match
// service_traits::DataType< ::mbf_msgs::CheckPath >
template<>
struct DataType< ::mbf_msgs::CheckPathResponse>
{
  static const char* value()
  {
    return DataType< ::mbf_msgs::CheckPath >::value();
  }
  static const char* value(const ::mbf_msgs::CheckPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MBF_MSGS_MESSAGE_CHECKPATH_H
