(cl:defpackage spencer_tracking_msgs-srv
  (:use )
  (:export
   "GETPERSONTRAJECTORIES"
   "<GETPERSONTRAJECTORIES-REQUEST>"
   "GETPERSONTRAJECTORIES-REQUEST"
   "<GETPERSONTRAJECTORIES-RESPONSE>"
   "GETPERSONTRAJECTORIES-RESPONSE"
  ))

