// Generated by gencpp from file pedsim_msgs/AgentGroup.msg
// DO NOT EDIT!


#ifndef PEDSIM_MSGS_MESSAGE_AGENTGROUP_H
#define PEDSIM_MSGS_MESSAGE_AGENTGROUP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace pedsim_msgs
{
template <class ContainerAllocator>
struct AgentGroup_
{
  typedef AgentGroup_<ContainerAllocator> Type;

  AgentGroup_()
    : header()
    , group_id(0)
    , age(0.0)
    , members()
    , center_of_mass()  {
    }
  AgentGroup_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , group_id(0)
    , age(0.0)
    , members(_alloc)
    , center_of_mass(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _group_id_type;
  _group_id_type group_id;

   typedef double _age_type;
  _age_type age;

   typedef std::vector<uint64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint64_t>> _members_type;
  _members_type members;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _center_of_mass_type;
  _center_of_mass_type center_of_mass;





  typedef boost::shared_ptr< ::pedsim_msgs::AgentGroup_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pedsim_msgs::AgentGroup_<ContainerAllocator> const> ConstPtr;

}; // struct AgentGroup_

typedef ::pedsim_msgs::AgentGroup_<std::allocator<void> > AgentGroup;

typedef boost::shared_ptr< ::pedsim_msgs::AgentGroup > AgentGroupPtr;
typedef boost::shared_ptr< ::pedsim_msgs::AgentGroup const> AgentGroupConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pedsim_msgs::AgentGroup_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pedsim_msgs::AgentGroup_<ContainerAllocator1> & lhs, const ::pedsim_msgs::AgentGroup_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.group_id == rhs.group_id &&
    lhs.age == rhs.age &&
    lhs.members == rhs.members &&
    lhs.center_of_mass == rhs.center_of_mass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pedsim_msgs::AgentGroup_<ContainerAllocator1> & lhs, const ::pedsim_msgs::AgentGroup_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pedsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pedsim_msgs::AgentGroup_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_msgs::AgentGroup_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_msgs::AgentGroup_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fd22ef81e8e7ee63e1028ae9b798458";
  }

  static const char* value(const ::pedsim_msgs::AgentGroup_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fd22ef81e8e7ee6ULL;
  static const uint64_t static_value2 = 0x3e1028ae9b798458ULL;
};

template<class ContainerAllocator>
struct DataType< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pedsim_msgs/AgentGroup";
  }

  static const char* value(const ::pedsim_msgs::AgentGroup_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint16 group_id\n"
"float64 age\n"
"uint64[] members\n"
"geometry_msgs/Pose center_of_mass\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pedsim_msgs::AgentGroup_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.group_id);
      stream.next(m.age);
      stream.next(m.members);
      stream.next(m.center_of_mass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentGroup_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pedsim_msgs::AgentGroup_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pedsim_msgs::AgentGroup_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "group_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.group_id);
    s << indent << "age: ";
    Printer<double>::stream(s, indent + "  ", v.age);
    s << indent << "members[]" << std::endl;
    for (size_t i = 0; i < v.members.size(); ++i)
    {
      s << indent << "  members[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.members[i]);
    }
    s << indent << "center_of_mass: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.center_of_mass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEDSIM_MSGS_MESSAGE_AGENTGROUP_H
